### ISSUE TITLE
Update export page

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/rakugo-docs#27]
Update export page for Godot 4.0

**Comment by Jeremi360** [comment]
How we should update it - you mean that now HTML5 export works under Firefox ?
But it was fixed by Godot 4.1 not Godot 4.0 or I'm am wrong ?

**Comment by theludovyc** [comment]
The fixing is not about a Godot version. Is an update of itch.io allow handle it properly with firefox.

On Godot4 the export form have been updated, so we need to update the screenshots

**Comment by Jeremi360** [comment]
@theludovyc
I finally sit down to updating docs.
I now don't see any setting for threads in HTML5 export,
so it is no longer need to change that?
![Peek 2024-03-02 19-52](https://github.com/rakugoteam/rakugo-docs/assets/1294815/b3383a9e-d551-4285-9a59-0bf2b2a24c34)

**Comment by Jeremi360** [comment]
Fixed by #31 , but I have a problem with deploying new docs

**Comment by Jeremi360** [comment]
finally deployed :grin: tomorrow I will make 2.2 update publised @theludovyc
