### ISSUE TITLE
Rkscript, update variable assignement

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/rakugo-docs#30]
We can use =, +=, -=, *=, /=

If we assign a string with variable in it, talk about it be replaced when get the value

**Comment by Jeremi360** [comment]
@theludovyc I finally sit down to updating docs so in docs about 2.2 it will be updated.

**Comment by Jeremi360** [comment]
It is updated:
- https://rakugoteam.github.io/rakugo-docs/2.2/rkvars/
- https://rakugoteam.github.io/rakugo-docs/2.2/rakugo_variables_workaround/
